export const API_PATHS = {
  LOGIN: `https://vadi.ixiono.tech/api/auth/signin`,
  SIGNUP: `https://vadi.ixiono.tech/api/auth/signup`,
  VALIDATE_OTP: `https://vadi.ixiono.tech/api/verifyOTP`,
  FORGET: `https://vadi.ixiono.tech/api/get-password-reset-link/`,
  RESEND_OTP: `https://vadi.ixiono.tech/api/auth/resendOTP/`,
  CREATE_PROFILE: `https://vadi.ixiono.tech/api/profile/create/`,
  FETCH_PROFILE: `https://vadi.ixiono.tech/api/profile/get-by-email`,
  VALIDATE_PASSWORD: `https://vadi.ixiono.tech/api/investor/validate-password/`,
  SEND_OTP: `https://vadi.ixiono.tech/api/sendOTP`,
  VERIFY_OTP: `https://vadi.ixiono.tech/api/verifySmsOTP`,
  MARKET_DATA: `https://vadi.ixiono.tech/api/wallet-coins/marketdata`,
  EXISTENCE_OF_WALLET: `https://vadi.ixiono.tech/wallet/User/check-existance-of-wallet/`,
  WALLET_SIGNUP: `https://vadi.ixiono.tech/wallet/User/auth/signUp`,
  WALLET_SIGNIN: `https://vadi.ixiono.tech/wallet/User/auth/signIn`,
  CREATE_WALLET: `https://vadi.ixiono.tech/wallet/vdc/create/wallet`,
  GET_BALANCES: `https://vadi.ixiono.tech/wallet/vdc/get/balances`,
  FRONT_DOC: `https://vadi.ixiono.tech/api/profile/file/upload/idFront/`,
  BACK_DOC: `https://vadi.ixiono.tech/api/profile/file/upload/idBackSide/`,
  ADDRESS_DOC: `https://vadi.ixiono.tech/api/profile/file/upload/idAddress/`,
};
